"""add async scan job persistence

Revision ID: ec83a758dcbd
Revises: f1881463ff5e
Create Date: 2026-07-05 05:11:35.759334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec83a758dcbd'
down_revision = 'f1881463ff5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('job_id', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_scan_history_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_history_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_scan_history_user_id_users', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('scan_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('job_id', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_scan_results_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_results_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_scan_results_user_id_users', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_results', schema=None) as batch_op:
        batch_op.drop_constraint('fk_scan_results_user_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_scan_results_user_id'))
        batch_op.drop_index(batch_op.f('ix_scan_results_job_id'))
        batch_op.drop_column('job_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('scan_history', schema=None) as batch_op:
        batch_op.drop_constraint('fk_scan_history_user_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_scan_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_scan_history_job_id'))
        batch_op.drop_column('job_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
