"""initial schema

Revision ID: f1881463ff5e
Revises: 
Create Date: 2026-07-05 04:55:53.128862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1881463ff5e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_date', sa.DateTime(), nullable=True),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('total_scanned', sa.Integer(), nullable=True),
    sa.Column('total_matched', sa.Integer(), nullable=True),
    sa.Column('filters_used', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.CheckConstraint("market IN ('stocks', 'crypto')", name='ck_scan_history_market'),
    sa.CheckConstraint("timeframe IN ('1min', '5min', '15min', '30min', '45min', '1H', '1D', '1W', '1M', '1Y')", name='ck_scan_history_timeframe'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('scan_type', sa.String(length=50), nullable=True),
    sa.Column('scan_date', sa.DateTime(), nullable=True),
    sa.Column('filters_matched', sa.Text(), nullable=True),
    sa.Column('indicator_values', sa.Text(), nullable=True),
    sa.Column('last_price', sa.Float(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('signal', sa.String(length=20), nullable=True),
    sa.CheckConstraint("market IN ('stocks', 'crypto')", name='ck_scan_results_market'),
    sa.CheckConstraint("timeframe IN ('1min', '5min', '15min', '30min', '45min', '1H', '1D', '1W', '1M', '1Y')", name='ck_scan_results_timeframe'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_results_scan_date'), ['scan_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_results_symbol'), ['symbol'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.CheckConstraint("plan IN ('free', 'premium')", name='ck_users_plan'),
    sa.CheckConstraint("role IN ('user', 'admin')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('watchlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint("market IN ('stocks', 'crypto')", name='ck_watchlists_market'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'symbol', name='uq_watchlists_user_symbol')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlists')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('scan_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_results_symbol'))
        batch_op.drop_index(batch_op.f('ix_scan_results_scan_date'))

    op.drop_table('scan_results')
    op.drop_table('scan_history')
    # ### end Alembic commands ###
